<template>
  <div>表名表</div>

  <div>
    123
  </div>

</template>
<script>
export default {
  name: "Sign",
  components: {},
  data() {
    return {
      formJson: {
        widgetList: [
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext60138",
              hidden: false,
              textContent: "单列表单",
              fontSize: "13px",
              customClass: [],
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext60138",
          },
          {
            type: "m-divider",
            icon: "divider",
            formItemFlag: false,
            options: {
              name: "mdivider72469",
              label: "",
              dashed: false,
              contentPosition: "center",
              hidden: false,
              customClass: [],
              onCreated: "",
              onMounted: "",
            },
            id: "mdivider72469",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "name",
              label: "Name (Chinese) 姓名 (中文)",
              labelAlign: "left",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "110",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: true,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: [],
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onChange: "",
              onFocus: "",
              onBlur: "",
              onValidate: "",
            },
            id: "minput21091",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "en_name",
              label: "(English)(英文)",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput44549",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "hongkong_FirstName",
              label: "Surname 姓",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput102423",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "hongkong_LastName",
              label: "Given Names 名",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput20875",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext34987",
              hidden: false,
              textContent:
                "(As shown on HKID Card or Passport 按香港身份證或護照所示)",
              fontSize: "13px",
              customClass: "",
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext34987",
          },
          {
            type: "m-date",
            icon: "date-field",
            formItemFlag: true,
            options: {
              name: "birthday",
              label: "Date of Birth 出生日期",
              labelAlign: "",
              defaultValue: null,
              placeholder: "",
              size: "",
              labelWidth: "80",
              labelHidden: false,
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              editable: false,
              format: "yyyy-MM-dd",
              minDate: "",
              maxDate: "",
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              labelIconClass: null,
              labelIconPosition: "rear",
              labelTooltip: null,
              onCreated: "",
              onMounted: "",
              onConfirm: "",
              onValidate: "",
            },
            id: "mdate45155",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "age",
              label: "Age年齡",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput99886",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "sex",
              label: "Sex性别",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput67602",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "hongkong-Id",
              label: "HKID/Passport No.香港身份證/護照號碼",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "131",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput68158",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "phone",
              label: "Tel. No.(Day)電話(日) ",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "80",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput59865",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "mobile",
              label: "Mobile手提電話（必須填寫）",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: true,
              requiredHint: "",
              validation: "number",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput86835",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "nationality",
              label: "Nationality國籍",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput56209",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "email",
              label: "Email Address電郵地址",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "100",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput81866",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "address",
              label: "Mailing Address通訊地址",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "110",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput12222",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "company",
              label: "Present Employer 現職公司/僱主名稱",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: "120",
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput41342",
          },
          {
            type: "m-input",
            icon: "text-field",
            formItemFlag: true,
            options: {
              name: "position",
              label: "Position 職位",
              labelAlign: "",
              type: "text",
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              leftIcon: "",
              rightIcon: "",
              appendButton: false,
              appendButtonType: "primary",
              appendButtonLabel: "",
              appendButtonIcon: "search",
              appendButtonDisabled: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onAppendButtonClick: "",
              onValidate: "",
            },
            id: "minput111737",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext50080",
              hidden: false,
              textContent: "Academic Qualifications 教育程度 : ",
              fontSize: "13px",
              customClass: ["font_700"],
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext50080",
          },
          {
            type: "m-radio",
            icon: "radio-field",
            formItemFlag: true,
            options: {
              name: "Qualifications",
              label: "",
              labelAlign: "left",
              defaultValue: "",
              iconSize: 20,
              direction: "vertical",
              labelWidth: "",
              labelHidden: false,
              readonly: false,
              disabled: false,
              hidden: false,
              dsEnabled: false,
              dsName: "",
              labelKey: "label",
              valueKey: "value",
              optionItems: [
                { label: "Primary/Secondary 小學/中學", value: 1 },
                { label: "Technical Institute 工業學院", value: 2 },
                { label: "College/University 專上學院/大學", value: 3 },
                { value: 4, label: "Others" },
              ],
              required: false,
              requiredHint: "",
              customClass: "",
              labelIconClass: null,
              labelIconPosition: "rear",
              labelTooltip: null,
              onCreated: "",
              onMounted: "",
              onChange: "\n\n\n\n\nconsele.log(value)",
              onValidate: "",
            },
            id: "mradio91568",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext63590",
              hidden: false,
              textContent: "Professional Qualifications 專業資格 :",
              fontSize: "13px",
              customClass: ["font_700"],
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext63590",
          },
          {
            type: "m-textarea",
            icon: "textarea-field",
            formItemFlag: true,
            options: {
              name: "Professional",
              label: "",
              labelAlign: "",
              rows: 3,
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onValidate: "",
            },
            id: "mtextarea95469",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext98791",
              hidden: false,
              textContent: "Course Fee 學費 HK$193",
              fontSize: "13px",
              customClass: ["font_700"],
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext98791",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext75371",
              hidden: false,
              textContent: "Payment method 付款方式",
              fontSize: "13px",
              customClass: "",
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext75371",
          },
          {
            type: "m-radio",
            icon: "radio-field",
            formItemFlag: true,
            options: {
              name: "payment_method",
              label: "",
              labelAlign: "",
              defaultValue: "",
              iconSize: 20,
              direction: "horizontal",
              labelWidth: null,
              labelHidden: false,
              readonly: false,
              disabled: false,
              hidden: false,
              dsEnabled: false,
              dsName: "",
              labelKey: "label",
              valueKey: "value",
              optionItems: [
                { label: "Cash 現金", value: 1 },
                { label: "Octopus 八達通", value: 2 },
                { label: "FPS 轉數快", value: 3 },
              ],
              required: false,
              requiredHint: "",
              customClass: "",
              labelIconClass: null,
              labelIconPosition: "rear",
              labelTooltip: null,
              onCreated: "",
              onMounted: "",
              onChange: "",
              onValidate: "",
            },
            id: "mradio120237",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext62997",
              hidden: false,
              textContent: "Declaration 聲明",
              fontSize: "13px",
              customClass: ["font_700"],
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext62997",
          },
          {
            type: "m-static-text",
            icon: "static-text",
            formItemFlag: false,
            options: {
              name: "mstatictext65303",
              hidden: false,
              textContent:
                "I declare that all information given in this application form is, to the best of my knowledge, accurate and complete. If any false information is given, the application is deemed to be invalid and I shall forfeit my right to apply for this course. I consent that if registered, I will conform to the regulations of Mlife Human Resources Development Centre.  本人聲明本報名表內所載一切資料，依本人所知均屬真確，並無遺漏，並知道倘若虛報資料，申請即屬無效，且喪失其後報讀本課程的資格。本人同意如本人註冊入學，當遵守德鑄人力資源發展中心之學生守則。",
              fontSize: "13px",
              customClass: "",
              onCreated: "",
              onMounted: "",
              label: "m-static-text",
            },
            id: "mstatictext65303",
          },
          {
            type: "m-textarea",
            icon: "textarea-field",
            formItemFlag: true,
            options: {
              name: "mtextarea54176",
              label: "Signature 簽名",
              labelAlign: "",
              rows: 3,
              defaultValue: "",
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              inputAlign: "left",
              readonly: false,
              disabled: false,
              hidden: false,
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              maxLength: null,
              showWordLimit: false,
              onCreated: "",
              onMounted: "",
              onInput: "",
              onFocus: "",
              onBlur: "",
              onValidate: "",
            },
            id: "mtextarea54176",
          },
          {
            type: "m-date",
            icon: "date-field",
            formItemFlag: true,
            options: {
              name: "date",
              label: "Date日期",
              labelAlign: "",
              defaultValue: null,
              placeholder: "",
              size: "",
              labelWidth: null,
              labelHidden: false,
              readonly: false,
              disabled: false,
              hidden: false,
              clearable: true,
              editable: false,
              format: "yyyy-MM-dd",
              minDate: "",
              maxDate: "",
              required: false,
              requiredHint: "",
              validation: "",
              validationHint: "",
              customClass: "",
              labelIconClass: null,
              labelIconPosition: "rear",
              labelTooltip: null,
              onCreated: "",
              onMounted: "",
              onConfirm: "",
              onValidate: "",
            },
            id: "mdate14414",
          },
          {
            type: "m-button",
            icon: "button",
            formItemFlag: false,
            options: {
              name: "submit",
              label: "提交按鈕",
              size: "normal",
              displayStyle: "block",
              disabled: false,
              hidden: false,
              type: "primary",
              plain: false,
              round: false,
              icon: null,
              customClass: [],
              onCreated: "",
              onMounted: "",
              onClick: "",
            },
            id: "mbutton49045",
          },
        ],
        formConfig: {
          modelName: "formData",
          refName: "vForm",
          rulesName: "rules",
          labelWidth: 120,
          labelAlign: "label-left-align",
          colon: false,
          inputAlign: "left",
          cssCode: ".font_700 {\n  font-weight: 700;  \n}\n",
          customClass: "",
          functions: "",
          layoutType: "H5",
          jsonVersion: -2,
          dataSources: [],
          onFormCreated: "",
          onFormMounted: "",
          onFormDataChange: "",
          labelPosition: "left",
          size: "",
        },
      },
      formData: {},
      optionData: {},
    };
  },
  created() {
    // window.addEventListener('storage', this.afterQRScan)
  },
  methods: {
    submitForm() {
      console.log("提交");
    },
  },
};
</script>

<style lang="scss">
/* 修复input 背景不协调 和光标变色 */
/* Detail see https://github.com/PanJiaChen/vue-element-admin/pull/927 */
</style>
